name = "Extremely-Simple"
license = "MIT"
licenselink = "https://github.com/xtod/Extremely-simple/blob/main/LICENSE"
description = "一款极致简洁的Hugo主题"
homepage = "https://github.com/xtod/Extremely-simple"
tags = ["blog", "minimalist","简洁"]
features = []
min_version = "0.1.0"

[author]
  name = "JQX"
  homepage = "unixetc.com"

# If porting an existing theme
[original]
  name = "riggraz"
  homepage = "https://riggraz.dev/"
  repo = "https://github.com/riggraz/no-style-please"
